package com.yc.liaolive.msg.model.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.yc.liaolive.msg.model.bean.ResetVoiceMessage;

import com.yc.liaolive.msg.model.bean.ResetVoiceMessageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig resetVoiceMessageDaoConfig;

    private final ResetVoiceMessageDao resetVoiceMessageDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        resetVoiceMessageDaoConfig = daoConfigMap.get(ResetVoiceMessageDao.class).clone();
        resetVoiceMessageDaoConfig.initIdentityScope(type);

        resetVoiceMessageDao = new ResetVoiceMessageDao(resetVoiceMessageDaoConfig, this);

        registerDao(ResetVoiceMessage.class, resetVoiceMessageDao);
    }
    
    public void clear() {
        resetVoiceMessageDaoConfig.clearIdentityScope();
    }

    public ResetVoiceMessageDao getResetVoiceMessageDao() {
        return resetVoiceMessageDao;
    }

}
